version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    # Temporarily comment out the volume for the initial build
    # volumes:
    #   - .:/var/www/html
    networks:
      - laravel_network
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: efimera
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
